# version: '3.9'

services:
  web1:
    build:
      context: .
      dockerfile: dockerfile
    networks:
      webnet:
        ipv4_address: 172.28.1.2  # IP statique pour web1
    # ports:
    #   - "6000:80"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=eduplateforme
      - DATABASE_USER=eduplateforme
      - DATABASE_PASSWORD=eduplateforme
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
    volumes:
      - media_data:/app/media

  web2:
    build:
      context: .
      dockerfile: dockerfile
    networks:
      webnet:
        ipv4_address: 172.28.1.3  # IP statique pour web2
    # ports:
    #   - "7000:80"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=eduplateforme
      - DATABASE_USER=eduplateforme
      - DATABASE_PASSWORD=eduplateforme
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
    volumes:
      - media_data:/app/media
      

  web3:
    build:
      context: .
      dockerfile: dockerfile
    networks:
      webnet:
        ipv4_address: 172.28.1.4  # IP statique pour web3
    # ports:
    #   - "8000:80"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=eduplateforme
      - DATABASE_USER=eduplateforme
      - DATABASE_PASSWORD=eduplateforme
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
    volumes:
      - media_data:/app/media
    

  db:
    image: mariadb:latest
    networks:
      webnet:
        ipv4_address: 172.28.1.5  # IP statique pour la base de données
    # ports:
    #   - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=eduplateforme
      - MYSQL_DATABASE=eduplateforme
      - MYSQL_USER=eduplateforme
      - MYSQL_PASSWORD=eduplateforme
    volumes:
      - db_data:/var/lib/mysql

  haproxy:
    build: ./haproxy
    networks:
      webnet:
        ipv4_address: 172.28.1.6  # IP statique pour HAProxy
    ports:
      - "80:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - web1
      - web2
      - web3

networks:
  webnet:
    driver: bridge  # Utilisation du driver 'bridge' pour le réseau
    ipam:
      config:
        - subnet: 172.28.1.0/24  # Sous-réseau pour tes conteneurs
          gateway: 172.28.1.1    # Passerelle pour le réseau
          
volumes:
  db_data:
  media_data:
